Added a new component: Stair Carousel
hsnice16/vanilla-web pull request #11
Opened 2024-05-15 08:53 UTC by PushpRatan

I have added a new component stair carousel and here is a little demo of it.

https://github.com/hsnice16/vanilla-web/assets/92618493/c48c1102-ec65-4be1-8f06-eafdec79d3d6

2024-05-19 13:54 UTC, hsnice16 requested changes
Great work with the component 🔥. I have just added a few comments.

2024-05-19 13:54 UTC, hsnice16 commented on index.html
> +        <!-- Stair carousel -->
All the components are arranged in alphabetical order. Please position this component accordingly.

2024-05-19 13:54 UTC, hsnice16 commented on stair-carousel/index.html
> +    <title>Dropdown Animation</title>
Update this title.

2024-05-19 13:54 UTC, hsnice16 commented on stair-carousel/script.js
> +  console.log(
Do we need this console log here?

2024-05-19 13:54 UTC, hsnice16 commented on stair-carousel/script.js
> +function FindPos(obj) {
Do we need this function? I think it is only printing a log to the console.
And, if needed, then any reasons to not use the camelCase naming convention here?

2024-05-19 13:54 UTC, hsnice16 commented on stair-carousel/styles.css
> +/* @charset "utf8";
If not needed, you can remove this comment.

2024-05-19 13:54 UTC, hsnice16 commented on stair-carousel/index.html
> +      <a class="selected" onclick="FindPos(this)" href="javascript:void(0);"
Any reasons to use an anchor tag `<a />` here if we are making them a dead link in the end?

2024-05-19 13:54 UTC, hsnice16 commented on stair-carousel/index.html
> +    <!-- <div class="gradientBRD"></div> -->
If not needed, you can remove this comment.

2024-05-19 13:54 UTC, hsnice16 commented on stair-carousel/styles.css
> +  /* height: 100%; */
If not needed, you can remove this comment.

2024-05-19 13:54 UTC, hsnice16 commented on stair-carousel/styles.css
> +.left:hover polyline, .left:focus polyline,
Check if we can use `:is()` function to compact this.

```
:is(.left, .right):is(:hover, :focus) polyline {
...
```

2024-05-22 06:04 UTC, PushpRatan commented
Thanks @hsnice16  for pointing out some of my mistakes. I have changed the code as you suggested.

2024-05-22 19:41 UTC, merged

2024-05-22 19:41 UTC, hsnice16 commented
Thanks for raising this PR @PushpRatan 🚀